export const enum TokenClassificationModels {
  DaylanBertBaseMultilingualCasedNerHrl = "Davlan/bert-base-multilingual-cased-ner-hrl",
  VblagojeBertEnglishUncasedFinetunedPos = "vblagoje/bert-english-uncased-finetuned-pos",
  DslimBertLargeNer = "dslim/bert-large-NER",
  DslimBertBaseNer = "dslim/bert-base-NER",
  Mrm8488BertSpanishCasedFinetunedPos16Tags = "mrm8488/bert-spanish-cased-finetuned-pos-16-tags",
  Mrm8488BertSpanishCasedFinetunedNer = "mrm8488/bert-spanish-cased-finetuned-ner",
  Mrm8488BertBaseGermanFinetunedLer = "mrm8488/bert-base-german-finetuned-ler",
  JeanBaptisteRobertaLargeNerEnglish = "Jean-Baptiste/roberta-large-ner-english",
  SshleiferTinyDistilbertBaseCased = "sshleifer/tiny-distilbert-base-cased",
  DslimBertBaseNerUncased = "dslim/bert-base-NER-uncased",
  DbmdzBertLargeCasedFinetunedConll03English = "dbmdz/bert-large-cased-finetuned-conll03-english",
  RajpurkarlabGilbert = "rajpurkarlab/gilbert",
  JeanBaptisteCamembertNer = "Jean-Baptiste/camembert-ner",
}
